spring.application.name=sysrestaurant
spring.datasource.url=jdbc:postgresql://localhost:5432/sysrestaurant
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.error.include-message=always
app.dev-tools.enabled=true
